### ISSUE TITLE
What the meaning of the max_distance?

### ISSUE THREAD

**Issue by yudawen** [geospatial-lab/building3d#1]

**Comment by shangfenghuang** [comment]
It corresponds to max_distance in the building3D.py file under the dataset file. It is used to normalize the data.

**Comment by yudawen** [comment]
How to restore all roof faces or triangular faces from a wireframe model, your provided *.obj file seems inconsistent with other people's *.obj files.

**Comment by yudawen** [comment]
Can you provide code for generating a wireframe model from wireframe

**Comment by yudawen** [comment]
Dear author, thank you for your time and for maintaining this great project.
Can you provide the code for your proposed supervised learning method?
I am very interested in your ICCV work, but it is difficult for me to finish the work you have done in your paper starting from scratch.
