### ISSUE TITLE
Need Help to train a model.

### ISSUE THREAD

**Issue by wahab-hac** [geospatial-lab/building3d#12]

**Comment by shangfenghuang** [comment]
Your work looks very interesting. 

What kind of help do you need?

**Comment by wahab-hac** [comment]
I need someone who can train the pointnet++ model or any model on my dataset and detect roofs and roof corners.
When i input a building file (single building file .obj)  it give me the output of pointclouds of roof corners in JSON.
My dataset consist of two Germany states. 
1. baden-württemberg state
2. rhineland-palatinate state

data is placed in folder format with precision like 
Country->State->City or Town->Street->Building
Germany->Baden-Württemberg->Achkarren-Kreuzmatten->Am Bahnhof ->1Building1

I can also gather all data in one folder.
