### ISSUE TITLE
How to get the supplementary materials mentioned in your paper ？

### ISSUE THREAD

**Issue by ShuaibZyx** [geospatial-lab/building3d#3]
Hello, Thanks for your great job. I'm interested in your work. The questions are following: 
I couldn't find any additional material that you mentioned in your paper, and I would like to know about the self-monitoring method you proposed in your paper. 
In addition, I did not find annotation information in the dataset I downloaded from the official website you provided, and you mentioned in the paper that your dataset can be used for semantic segmentation tasks, which is very helpful for me. Thank you very much for your answer.

**Comment by shangfenghuang** [comment]
I'm so sorry for responding to questions so late.

The self-supervised method can be found in this paper https://ieeexplore.ieee.org/document/10423095

The semantic segmentation task is an additional addition. Such data will not be made available for the time being
