### ISSUE TITLE
Sampling a point cloud from provided meshes produces weird line-like artifacts

### ISSUE THREAD

**Issue by kdmayer** [geospatial-lab/building3d#8]
Hi,

I've noticed that when sampling a point cloud from the provided .obj files, many of the generated point clouds exhibit weird line-like artifacts (see screenshot below):

![Screenshot 2024-06-07 at 6 12 36 PM](https://github.com/geospatial-lab/Building3D/assets/49768291/168eebef-deef-4d02-a109-049ead4c7411)

Any idea on why this is and how it can be fixed?

`      
import open3d as o3d
import numpy as np

mesh = o3d.io.read_triangle_mesh(PATH_TO_OBJ_FILE)
point_cloud = np.asarray(mesh.sample_points_poisson_disk(number_of_points=10000).points)
`

Note that these line-like artifacts appear with poisson as well as uniform sampling.

Thank you,
Kevin

**Comment by shangfenghuang** [comment]
I think that it could be a visualization problem.

![image](https://github.com/geospatial-lab/Building3D/assets/45654745/9bfb049e-0dd4-4bb3-901a-9ed7e0c901af)

o3d.visualization.draw_geometries([point_cloud], window_name="Poisson Disk Sampling")


From your results, the xyz values of point cloud seem to be truncated.
For example. 4.235 may be seen as 4.2, and 4.279 also is be seen as 4.2.  It means the values between 4.2 and 4.29999... are seen as 4.2.
so it looks like the line-like artifacts.

You can use the cloudcompare to visualizate the point clouds.

**Comment by kdmayer** [comment]
Hi,

Yes, in fact, it was a numerical overflow issue, because the coordinates in EPSG:3301 are so large. Applying a global shift to the point clouds before visualization resolves the issue.

Thank you!
